name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate SHA
      id: gererate_sha
      run: | 
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT
        
    - name: Login into the container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}  

    - name: Build docker image
      run: docker build -t marcelocaldasdevops/nlw-journey-devops:${{ steps.gererate_sha.outputs.sha}} .
    - name: Push image 
      run: |
        docker push marcelocaldasdevops/nlw-journey-devops:${{ steps.gererate_sha.outputs.sha}}
        docker tag  marcelocaldasdevops/nlw-journey-devops:${{ steps.gererate_sha.outputs.sha}} marcelocaldasdevops/nlw-journey-devops:latest
        docker push marcelocaldasdevops/nlw-journey-devops:latest